# Generated by Django 4.2.6 on 2024-02-13 06:17

from django.db import migrations, models
import django_countries.fields
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('applicant_id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('interested_for', models.CharField(choices=[('Work From Home (WFH)', 'Work From Home (WFH)'), ('Work From Office (WFO)', 'Work From Office (WFO)')], default='Work From Home (WFH)', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('want_to_work', models.CharField(choices=[('Morning (7 am - 3 pm)', 'Morning (7 am - 3 pm)'), ('Evening (3 pm - 11 pm)', 'Evening (3 pm - 11 pm)'), ('Night (11 pm - 7 am)', 'Night (11 pm - 7 am)')], default='Morning (7 am - 3 pm)', max_length=50)),
                ('highest_education', models.CharField(choices=[('Completed 10 years school', 'Completed 10 years school'), ('University Degree', 'University Degree'), ('University Degree - Masters', 'University Degree - Masters'), ('Technical Degree', 'Technical Degree'), ('Others', 'Others')], default='Completed 10 years school', max_length=100)),
                ('country', django_countries.fields.CountryField(default='BD', max_length=2, null=True)),
                ('earliest_start_date', models.DateField()),
                ('national_id', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to='temp_cv/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Temp_pictures/')),
                ('meeting_link_sent', models.BooleanField(default=False)),
                ('account_create', models.BooleanField(default=False)),
            ],
        ),
    ]
